import { Product } from "@/types";
import { nanoid } from "nanoid";

export const SEED_PRODUCTS: Product[] = [
    {
        id: "1",
        title: "Nova Pro Max X",
        shortDesc: "The ultimate smartphone for professionals.",
        fullDesc: "Experience the pinnacle of mobile technology with the Nova Pro Max X. Featuring a stunning 6.9-inch Titanium OLED display, the most powerful A20 chip ever made, and a revolutionary triple-lens camera system that captures reality like never before.",
        price: 1299,
        category: "Smartphone",
        image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop",
        createdAt: new Date(),
    },
    {
        id: "2",
        title: "ZenBook Ultra 14",
        shortDesc: "Power meets portability in this sleek laptop.",
        fullDesc: "Crafted for creators and dreamers, the ZenBook Ultra 14 delivers uncompromising performance in an impossibly thin chassis. With 32GB of RAM and 1TB of SSD storage, your workflow will never slow down.",
        price: 1899,
        category: "Laptop",
        image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=800&auto=format&fit=crop",
        createdAt: new Date(),
    },
    {
        id: "3",
        title: "SonicWave Buds",
        shortDesc: "Crystal clear audio with active noise cancellation.",
        fullDesc: "Immerse yourself in pure sound with SonicWave Buds. Our proprietary noise cancellation technology blocks out 99% of ambient noise, letting you focus on the music that matters.",
        price: 199,
        category: "Audio",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop",
        createdAt: new Date(),
    },
    {
        id: "4",
        title: "Nova Watch Series 5",
        shortDesc: "Your health and fitness companion.",
        fullDesc: "Track your every move and monitor your health with precision. The Nova Watch Series 5 features advanced heart rate monitoring, sleep tracking, and a 5-day battery life.",
        price: 349,
        category: "Wearable",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop",
        createdAt: new Date(),
    },
    {
        id: "5",
        title: "CinemaLens 4K",
        shortDesc: "Capture cinematic moments in stunning 4K.",
        fullDesc: "The CinemaLens 4K brings professional filmmaking to everyone. With its large sensor and exceptional low-light performance, every shot is a masterpiece.",
        price: 2499,
        category: "Camera",
        image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop",
        createdAt: new Date(),
    },
    {
        id: "6",
        title: "Aura Headphones",
        shortDesc: "Premium over-ear comfort with studio sound.",
        fullDesc: "Designed for audiophiles, the Aura Headphones provide a wide soundstage and incredible detail. The memory foam cushions ensure comfort for even the longest listening sessions.",
        price: 449,
        category: "Audio",
        image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop",
        createdAt: new Date(),
    },
    {
        id: "7",
        title: "Nexus Tablet Pro",
        shortDesc: "The most versatile tablet for work and play.",
        fullDesc: "Whether you're sketching your next masterpiece or managing complex projects, the Nexus Tablet Pro is the perfect tool. Compatible with the Nexus Pen and Smart Keyboard.",
        price: 899,
        category: "Accessory",
        image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800&auto=format&fit=crop",
        createdAt: new Date(),
    },
    {
        id: "8",
        title: "SwiftCharge Dock",
        shortDesc: "Fast wireless charging for all your devices.",
        fullDesc: "Keep your devices powered up with the SwiftCharge Dock. Charges your phone, watch, and earbuds simultaneously with up to 25W of power.",
        price: 129,
        category: "Accessory",
        image: "https://images.unsplash.com/photo-1615526675159-e248c3021d3f?q=80&w=800&auto=format&fit=crop",
        createdAt: new Date(),
    },
];
